[package]
name = "rterrain"
version = "0.1.0"
authors = ["Michael Wang <mwwpublic@gmail.com>"]

[dependencies]
rterrain-average-neighbor = { version = "*", path = "./average-neighbor" }

[dev-dependencies]
image = "*"
