[package]
name = "rterrain"
version = "0.1.0"
authors = ["Michael Wang <mwwpublic@gmail.com>"]

[dependencies]
rterrain_average_neighbor = { version = "*", path = "./average_neighbor" }

[dev-dependencies]
image = "*"
