[package]
name = "rterrain_average_neighbor"
version = "0.1.0"
authors = ["Michael Wang <mwwpublic@gmail.com>"]

[lib]
crate-type = ['dylib']

[dependencies]
rterrain_math = { version = "*", path = "../math" }
